### PR TITLE
Add csv archive support to signature scan invocation

### PR DESCRIPTION
**Pull request by dterrysynopsys**
This allows for passing a csv archive option to the signature scanner so that csv files can be created. Detect will begin doing this in offline mode so that users have access to the files.

### CODE REVIEW

**Review by andrian-sevastyanov — APPROVED** [review]

**Review by ChomickiM — APPROVED** [review]

**Comment by gopannabd** [comment]
Is --outputFormat customer facing?

**Comment by dterrysynopsys** [comment]
> Is --outputFormat customer facing?

It is in the sense that you could run the scan CLI manually and specify it. This work is so that Detect can essentially ask for it to be added once we add a new specific Detect property.

**Comment by gopannabd** [comment]
Will there be a Detect property that customer could set to enable this property? Or, is it going to be enabled by default in offline mode?

**Comment by dterrysynopsys** [comment]
> Will there be a Detect property that customer could set to enable this property? Or, is it going to be enabled by default in offline mode?

Yes, this is the prep work for that. Another PR will be made on the Detect side to add the property.

**Pull request merged**
